version: '2'

services:
  oracle-db:
    build:
      context: .
    image: oracle/database:11.2.0.2-xe
    container_name: oracle-db
    shm_size: 1g
    ports:
      - 1521:1521
      - 18080:8080
    networks:
      - docker_network
    volumes:
      - ./data/oracle/oradata:/u01/app/oracle/oradata
      - /home/xo/aurea/vm-share/db_dump:/u01/app/oracle/DATAPUMP

networks:
  docker_network:
    driver: bridge

